### ISSUE TITLE
Where to find the fingerprint matching algorithm

### ISSUE THREAD

**Issue by zy-zy-zy** [ivonajdenkoska/fingerprint-recognition#3]
Hello Ivona,

Thanks for this great project! I am very interested in the fingerprint matching part. May I ask where to find the corresponding paper or other materials which have a detailed description of the fingerprint matching algorithm as implemented in this project? Thanks so much!

Best,
zy

**Comment by zy-zy-zy** [comment]
Just found that the algorithm is ORB in the jupyter notebook file. Will do more research on it. But still, any recommendation is deeply appreciated.

**Comment by ivonajdenkoska** [comment]
Hello Zy,

I would recommend the following book: Introduction to Biometrics (Authors: Jain, Anil K., Ross, Arun A., Nandakumar, Karthik). There is a really nice overview of fingerprint recognition in Chapter 2, including the matching algorithms.

Hope it helps,
Ivona

**Comment by JinZhuXing** [comment]
Hello.
I am currently developing a fingerprint recognition system using Tenseflow 2. 
(https://github.com/JinZhuXing/Fingerprint_TF)
I haven't finished this project yet, but I hope it helps you.
Thanks.

**Comment by zy-zy-zy** [comment]
> Hello Zy,
> 
> I would recommend the following book: Introduction to Biometrics (Authors: Jain, Anil K., Ross, Arun A., Nandakumar, Karthik). There is a really nice overview of fingerprint recognition in Chapter 2, including the matching algorithms.
> 
> Hope it helps,
> Ivona

Thanks so much Ivona! Really appreciate it.

**Comment by zy-zy-zy** [comment]
> Hello.
> I am currently developing a fingerprint recognition system using Tenseflow 2.
> (https://github.com/JinZhuXing/Fingerprint_TF)
> I haven't finished this project yet, but I hope it helps you.
> Thanks

Thanks! Fingerprint match based on deep learning is also what I am looking for. Great project!
